### ISSUE TITLE
Cannot use now?

### ISSUE THREAD

**Issue by timeanddoctor** [pariterre/KinoveaAnalyse#1]
Cannot use now?

**Comment by timeanddoctor** [comment]
Or I cannot find the lib of bio>?

**Comment by pariterre** [comment]
Hello timeanddoctor,
This is a waiting project since I was working on pyomeca library and ezc3d projects during the summer. The script "Analyse.py" should run without problem and output the same figure as the one in "output.png". 
For now, there is a mixture of french and english because I created this script for my students in a lecture in biomechanics I gave last year. 

To run the example analysis, you should only have to make sure python 3.6+ is install, and the packages matplotlib and numpy. I taged a video with 6 markers ("Hanche" [Hip], "Genou" [Knee], "Malleole", "Pied" [Foot], "Epaule" [Shoulder], "Coude" [Elbow], "Main" [Hand], "Tete" [Head]). For now on (but it will be corrected in the future), the markers must have these names (unless you change the "reperes_anato" variable and corresponding values in the winter table).

What do you mean by "cannot find the lib of bio"?

**Comment by timeanddoctor** [comment]
Thank you Professor Pariterre
I will try to do follow your opinion. I maked a mistake between the matplotlib and the "biomechanical library".
What I am doing is to get a “Match sticks” picture based on Kinovea (Fig.1).  A professor told me that I can make a Figure with Matlab based on the data from Kinovea. However, I am confused. Because I am not familiar with Matlab, espencially which is a commercial software. So I try to use gnuplot (http://www.gnuplot.info/) for my study. And could you give me any advise, Thanks!

Fig.1
![2018-08-17_212615](https://user-images.githubusercontent.com/28825816/44269278-9da4fe80-a266-11e8-9440-e1378a3f4f72.jpg)

**Comment by pariterre** [comment]
Hello timeanddoctor,
A priori, assuming you change the name of the markers accordingly, the script Analyse.py should do what you want. However, for now, it is not in the form of a kinogram, but at a specific frame (the variable `time_idx`). You can modify this variable and add a for loop to do the calculation at each frame and then plot everything. 

In brief, the stick code as it stand should provide you with a stick figure as you need for one frame

**Comment by timeanddoctor** [comment]
I installed anocoda and run "conda env create -f env.yml", while the script(analyse,py) seems to get an error just like the Figures.(the table was coped from example document)
![2018-08-18_104028](https://user-images.githubusercontent.com/28825816/44295138-b8628c00-a2d5-11e8-98a3-455dde041e89.jpg)
![2018-08-18_103214](https://user-images.githubusercontent.com/28825816/44295139-bac4e600-a2d5-11e8-8b31-74e2567cb505.jpg)




 

Thank you very much !
I am a neurosurgery doctor and difficult to complet the task "modify time_idx variable and add a for loop to do the calculation at each frame and then plot everything" Could you help me complet the code edit. Thanks!

**Comment by timeanddoctor** [comment]
![2018-08-18_100656](https://user-images.githubusercontent.com/28825816/44298367-465d6780-a314-11e8-87f1-b974bba15ca5.jpg)
translater to Chinese by Google

**Comment by timeanddoctor** [comment]
sorry to closed.....

**Comment by pariterre** [comment]
Hi timeanddoctor, 
I'm glad you could make it work. Just for your information I added a portion of the code that creates a kinogram as you needed it ;)
Enjoy!

**Comment by timeanddoctor** [comment]
Dear Professor Pariterre
Thank you very much !
There is a error ? I will capture a video later.

**Comment by timeanddoctor** [comment]
image[http://p5x89vpof.bkt.clouddn.com/2018-08-18_212027.jpg]

**Comment by timeanddoctor** [comment]
http://p5x89vpof.bkt.clouddn.com/Video_2018-08-18_211609.wmv

**Comment by timeanddoctor** [comment]
![video_2018-08-18_211609](https://user-images.githubusercontent.com/28825816/44299760-ab25bb80-a32e-11e8-85f1-5df5d329d163.gif)

**Comment by pariterre** [comment]
Hi timeanddoctor, 
I'm glad you could make it work. Just for your information I added a portion of the code that creates a kinogram as you needed it ;)
Enjoy!

**Comment by pariterre** [comment]
Hi timeanddoctor,
After `cd` to the directory, you should load the environment using the command `source activate Kinovea`or `conda activate Kinovea` (this is assuming you previously installed the environment using the `conda env create -f env.yml` command.
Thereafter, you can launch the software with the command `python Analyse.py`. It should work ;)

**Comment by timeanddoctor** [comment]
Dear Professor Pariterre
I have runned the Py file follow your advise, however there is still a error.... 
After google xlm.etree and %H:%M,et al , I get nothing could help me...
I am a newable to python even I try my best to learn to deal with the problem, but it seems so difficult to me.
![2018-08-20_105837](https://user-images.githubusercontent.com/28825816/44318474-be3ca680-a468-11e8-95e7-99543d7d2fc0.jpg)

**Comment by timeanddoctor** [comment]
![test](https://user-images.githubusercontent.com/28825816/44318557-681c3300-a469-11e8-87c8-f87a05889c59.gif)

**Comment by pariterre** [comment]
Hello again,

In this last video everything up to the run of `Analyse.py` is okay. For this last part, you forgot `python` before `Analyse.py`. The command should read: `python Analyse.py`

**Comment by timeanddoctor** [comment]
the test "video-new" as !
![test3](https://user-images.githubusercontent.com/28825816/44320819-e6330680-a476-11e8-9008-d0d437424d41.gif)

**Comment by timeanddoctor** [comment]
my system is WIN7*64. I captured my Conda  enviroment for Kinovea
"ENV-NEW" AS
![test](https://user-images.githubusercontent.com/28825816/44320639-d36c0200-a475-11e8-9fac-b7ba4e8cf51e.gif)

**Comment by pariterre** [comment]
Hello
As I said everything you did in the video before my last comment was perfect. The only mistake was that you forgot to type `python` before.

**Comment by timeanddoctor** [comment]
![2018-08-21_073209](https://user-images.githubusercontent.com/28825816/44372019-90ad3700-a514-11e8-8d62-c564299d0faf.jpg)
I did it "python analyse.py" on promt
but still .....like picture

**Comment by pariterre** [comment]
Hello!
It seems that the it struggle to read the xml file (the xml is supposed to be the Kinovea output). Can you send it to me?

**Comment by timeanddoctor** [comment]
Thanks!
The xml file download directly from your code:KinoveaAnalyse/example/box_jump.xml

**Comment by timeanddoctor** [comment]
![360 -66760877](https://user-images.githubusercontent.com/28825816/44443232-51144700-a609-11e8-8466-b7486d84dcea.jpg)

**Comment by timeanddoctor** [comment]
A new tool for analysing of Gait :https://github.com/AlexEMG/DeepLabCut
