### ISSUE TITLE
Améliorations pédagogiques

### ISSUE THREAD

**Issue by ArianeCR** [pariterre/KinoveaAnalyse#2]
Bonjour!! 
J'aimerais utiliser le logiciel avec des étudiants et pour rendre la tâche plus simple, serait-il possible de : 

- faire apparaître une boite pop up pour entrer les paramètres variables : Frame #, masse et nom du fichier. 

- faire apparaître la ligne associée au frame choisi dans les graphs du outpout 

- faire apparaître la valeur calculée pour la hauteur du CoM à l'instant choisi (dans le titre? «hauteur du CoM : .......) 
Merci beaucoup! :)

**Comment by pariterre** [comment]
Bonjour @ArianeCR ,

Merci de l'intérêt que vous portez à KinoveaAnalyse!
Vu l'enthousiasme de votre demande, j'ai rapidement mis à jour le logiciel :)

Pouvez-vous me dire, si le tout vous convient?

Bien à vous et pour toujours
